import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import fr from './locales/fr.json'
import en from './locales/en.json'
import ru from './locales/ru.json'
import es from './locales/es.json'
import hi from './locales/hi.json'
import zh from './locales/zh.json'
import { translations } from './data/translations'
import { uiTranslations } from './data/uiTranslations'

const dossierTranslations = {
  fr: { eyebrow: 'Nouvelle demande', title: 'Ouvrir un dossier', service: 'Prestation', service_placeholder: 'Sélectionner une prestation', nationality: 'Nationalité', nationality_placeholder: 'Ex : Camerounaise', destination: 'Destination', destination_placeholder: 'Ex : France', motif: 'Motif de la demande', motif_placeholder: 'Décrivez le motif de votre demande...', document: 'Pièce justificative', file_hint: 'Formats acceptés : PDF, JPG, PNG · Max 5 Mo', submit: 'Soumettre le dossier', submitting: 'Envoi en cours...', success_title: 'Dossier soumis avec succès !', success_desc: 'Votre dossier a été créé. Un conseiller vous contactera sous 24h.', redirecting: 'Redirection vers votre espace client...', err_service: 'Veuillez choisir une prestation', err_nationality: 'La nationalité est requise', err_motif: 'Le motif est requis', err_document: 'Au moins un document est requis', err_document_type: 'Le document doit être au format PDF, JPG ou PNG.', err_document_size: 'Le document ne doit pas dépasser 5 Mo.' },
  en: { eyebrow: 'New request', title: 'Open a file', service: 'Service', service_placeholder: 'Select a service', nationality: 'Nationality', nationality_placeholder: 'e.g. Cameroonian', destination: 'Destination', destination_placeholder: 'e.g. France', motif: 'Reason for request', motif_placeholder: 'Describe the reason for your request...', document: 'Supporting document', file_hint: 'Accepted formats: PDF, JPG, PNG · Max 5 MB', submit: 'Submit file', submitting: 'Submitting...', success_title: 'File submitted successfully!', success_desc: 'Your file has been created. An advisor will contact you within 24h.', redirecting: 'Redirecting to your client area...', err_service: 'Please choose a service', err_nationality: 'Nationality is required', err_motif: 'Reason is required', err_document: 'At least one document is required', err_document_type: 'The document must be a PDF, JPG or PNG file.', err_document_size: 'The document must not exceed 5 MB.' },
  ru: { eyebrow: 'Новый запрос', title: 'Открыть дело', service: 'Услуга', service_placeholder: 'Выберите услугу', nationality: 'Гражданство', nationality_placeholder: 'Например: Камерун', destination: 'Направление', destination_placeholder: 'Например: Франция', motif: 'Причина запроса', motif_placeholder: 'Опишите причину вашего запроса...', document: 'Подтверждающий документ', file_hint: 'Допустимые форматы: PDF, JPG, PNG · Макс. 5 МБ', submit: 'Отправить дело', submitting: 'Отправка...', success_title: 'Дело успешно отправлено!', success_desc: 'Ваше дело создано. Консультант свяжется с вами в течение 24 часов.', redirecting: 'Перенаправление в личный кабинет...', err_service: 'Выберите услугу', err_nationality: 'Требуется гражданство', err_motif: 'Требуется причина', err_document: 'Необходим хотя бы один документ', err_document_type: 'Документ должен быть в формате PDF, JPG или PNG.', err_document_size: 'Размер документа не должен превышать 5 МБ.' },

  es: {eyebrow:"Nueva solicitud",title:"Abrir un expediente",service:"Trámite",service_placeholder:"Seleccionar un trámite",nationality:"Nacionalidad",nationality_placeholder:"Ej.: Camerunesa",destination:"Destino",destination_placeholder:"Ej.: Francia",motif:"Motivo de la solicitud",motif_placeholder:"Describa el motivo de su solicitud...",document:"Documento justificativo",file_hint:"Formatos aceptados: PDF, JPG, PNG · Máx. 5 MB",submit:"Enviar el expediente",submitting:"Enviando...",success_title:"¡Expediente enviado con éxito!",success_desc:"Su expediente ha sido creado. Un asesor le contactará en un plazo de 24 h.",redirecting:"Redirigiendo a su área de cliente...",err_service:"Elija un trámite",err_nationality:"La nacionalidad es obligatoria",err_motif:"El motivo es obligatorio",err_document:"Se requiere al menos un documento",err_document_type:"El documento debe estar en formato PDF, JPG o PNG.",err_document_size:"El documento no debe superar los 5 MB."},
  hi: {eyebrow:"नया अनुरोध",title:"केस खोलें",service:"सेवा",service_placeholder:"सेवा चुनें",nationality:"राष्ट्रीयता",nationality_placeholder:"उदा.: कैमरून",destination:"गंतव्य",destination_placeholder:"उदा.: फ्रांस",motif:"अनुरोध का कारण",motif_placeholder:"अपने अनुरोध का कारण बताएं...",document:"समर्थन दस्तावेज़",file_hint:"स्वीकृत प्रारूप: PDF, JPG, PNG · अधिकतम 5 MB",submit:"केस जमा करें",submitting:"जमा हो रहा है...",success_title:"केस सफलतापूर्वक जमा किया गया!",success_desc:"आपका केस बन गया है। सलाहकार 24 घंटे में संपर्क करेगा।",redirecting:"आपके ग्राहक क्षेत्र पर पुनर्निर्देशित...",err_service:"कृपया सेवा चुनें",err_nationality:"राष्ट्रीयता आवश्यक है",err_motif:"कारण आवश्यक है",err_document:"कम से कम एक दस्तावेज़ आवश्यक है",err_document_type:"दस्तावेज़ PDF, JPG या PNG प्रारूप में होना चाहिए।",err_document_size:"दस्तावेज़ 5 MB से अधिक नहीं होना चाहिए।"},
  zh: {eyebrow:"新申请",title:"创建档案",service:"服务",service_placeholder:"请选择服务",nationality:"国籍",nationality_placeholder:"例如：喀麦隆",destination:"目的地",destination_placeholder:"例如：法国",motif:"申请事由",motif_placeholder:"请描述您的申请事由...",document:"证明文件",file_hint:"支持的格式：PDF、JPG、PNG · 最大 5 MB",submit:"提交档案",submitting:"提交中...",success_title:"档案提交成功！",success_desc:"您的档案已创建，顾问将在 24 小时内与您联系。",redirecting:"正在跳转到客户中心...",err_service:"请选择服务",err_nationality:"必须填写国籍",err_motif:"必须填写事由",err_document:"至少需要一个文件",err_document_type:"文件必须为 PDF、JPG 或 PNG 格式。",err_document_size:"文件不得超过 5 MB。"},
}

const interfaceTranslations = {
  fr: { client_dashboard: { my_files: 'Mes dossiers', loading: 'Chargement...', retry: 'Réessayer', load_error: 'Impossible de charger vos données client.', no_file: 'Aucun dossier', no_file_description: "Aucun dossier n'est encore enregistré pour votre compte.", first_file: 'Créer mon premier dossier', details: 'Voir le détail', my_orders: 'Mes commandes', no_order: 'Aucune réservation confirmée.', passenger: 'passager', ticket: 'Voir le billet', cancel: 'Annuler', appointments: 'Mes rendez-vous', no_appointment: 'Aucun rendez-vous planifié.', make_appointment: 'Prendre rendez-vous', notifications: 'Voir mes notifications', quick_access: 'Accès rapide', services_catalogue: 'Catalogue des prestations', book_ticket: 'Réserver un billet', profile_hint: 'Votre profil est associé à l’adresse saisie lors de la connexion.' }, service_detail: { eyebrow: 'Prestation', delay: 'Délai', documents: 'Pièces nécessaires', open_file: 'Ouvrir un dossier', loading: 'Chargement de la prestation...', unavailable: 'Prestation introuvable', unavailable_description: "Cette prestation n'existe pas ou n'est plus disponible.", back: 'Retour au catalogue', load_error: 'Impossible de charger cette prestation.' }, notifications: { eyebrow: 'Suivi', title: 'Notifications', empty: 'Aucune notification pour le moment.' }, footer: { tagline: 'Mobilité et démarches simplifiées', copyright: 'Tous droits réservés.', services: 'Prestations', journeys: 'Trajets' }, status: { pending: 'En attente', en_cours: 'En cours', en_validation: 'En validation', documents_requis: 'Pièces manquantes', confirmed: 'Confirmé', paid: 'Payé', cancelled: 'Annulé', accepted: 'Accepté', default: 'À traiter' } },
  en: { client_dashboard: { my_files: 'My files', loading: 'Loading...', retry: 'Retry', load_error: 'Unable to load your client data.', no_file: 'No files', no_file_description: 'No file has been registered for your account yet.', first_file: 'Create my first file', details: 'View details', my_orders: 'My orders', no_order: 'No confirmed booking.', passenger: 'passenger', ticket: 'View ticket', cancel: 'Cancel', appointments: 'My appointments', no_appointment: 'No appointment scheduled.', make_appointment: 'Make an appointment', notifications: 'View my notifications', quick_access: 'Quick access', services_catalogue: 'Services catalogue', book_ticket: 'Book a ticket', profile_hint: 'Your profile is linked to the email address used when signing in.' }, service_detail: { eyebrow: 'Service', delay: 'Processing time', documents: 'Required documents', open_file: 'Open a file', loading: 'Loading service...', unavailable: 'Service unavailable', unavailable_description: 'This service does not exist or is no longer available.', back: 'Back to catalogue', load_error: 'Unable to load this service.' }, notifications: { eyebrow: 'Tracking', title: 'Notifications', empty: 'No notifications at the moment.' }, footer: { tagline: 'Mobility and simplified procedures', copyright: 'All rights reserved.', services: 'Services', journeys: 'Journeys' }, status: { pending: 'Pending', en_cours: 'In progress', en_validation: 'In validation', documents_requis: 'Missing documents', confirmed: 'Confirmed', paid: 'Paid', cancelled: 'Cancelled', accepted: 'Accepted', default: 'To process' } },
  ru: { client_dashboard: { my_files: 'Мои дела', loading: 'Загрузка...', retry: 'Повторить', load_error: 'Не удалось загрузить данные клиента.', no_file: 'Нет дел', no_file_description: 'Для вашей учётной записи пока нет дел.', first_file: 'Создать первое дело', details: 'Подробнее', my_orders: 'Мои заказы', no_order: 'Нет подтверждённых бронирований.', passenger: 'пассажир', ticket: 'Посмотреть билет', cancel: 'Отменить', appointments: 'Мои встречи', no_appointment: 'Нет запланированных встреч.', make_appointment: 'Записаться на встречу', notifications: 'Посмотреть уведомления', quick_access: 'Быстрый доступ', services_catalogue: 'Каталог услуг', book_ticket: 'Забронировать билет', profile_hint: 'Ваш профиль связан с адресом электронной почты, указанным при входе.' }, service_detail: { eyebrow: 'Услуга', delay: 'Срок обработки', documents: 'Необходимые документы', open_file: 'Открыть дело', loading: 'Загрузка услуги...', unavailable: 'Услуга не найдена', unavailable_description: 'Эта услуга не существует или больше недоступна.', back: 'Вернуться в каталог', load_error: 'Не удалось загрузить эту услугу.' }, notifications: { eyebrow: 'Отслеживание', title: 'Уведомления', empty: 'Сейчас уведомлений нет.' }, footer: { tagline: 'Мобильность и упрощённые процедуры', copyright: 'Все права защищены.', services: 'Услуги', journeys: 'Маршруты' }, status: { pending: 'Ожидание', en_cours: 'В работе', en_validation: 'На проверке', documents_requis: 'Необходимы документы', confirmed: 'Подтверждено', paid: 'Оплачено', cancelled: 'Отменено', accepted: 'Принято', default: 'В обработку' } },

  es: {client_dashboard:{my_files:"Mis expedientes",loading:"Cargando...",retry:"Reintentar",load_error:"No se pudieron cargar sus datos de cliente.",no_file:"Ningún expediente",no_file_description:"Todavía no hay expedientes registrados en su cuenta.",first_file:"Crear mi primer expediente",details:"Ver el detalle",my_orders:"Mis pedidos",no_order:"Ninguna reserva confirmada.",passenger:"pasajero",ticket:"Ver el billete",cancel:"Cancelar",appointments:"Mis citas",no_appointment:"Ninguna cita programada.",make_appointment:"Pedir una cita",notifications:"Ver mis notificaciones",quick_access:"Acceso rápido",services_catalogue:"Catálogo de trámites",book_ticket:"Reservar un billete",profile_hint:"Su perfil está vinculado al correo electrónico utilizado al iniciar sesión."},service_detail:{eyebrow:"Trámite",delay:"Plazo",documents:"Documentos necesarios",open_file:"Abrir un expediente",loading:"Cargando el trámite...",unavailable:"Trámite indisponible",unavailable_description:"Este trámite no existe o ya no está disponible.",back:"Volver al catálogo",load_error:"No se pudo cargar este trámite."},notifications:{eyebrow:"Seguimiento",title:"Notificaciones",empty:"Ninguna notificación por el momento."},footer:{tagline:"Movilidad y trámites simplificados",copyright:"Todos los derechos reservados.",services:"Trámites",journeys:"Viajes"},status:{pending:"Pendiente",en_cours:"En curso",en_validation:"En verificación",documents_requis:"Documentos pendientes",confirmed:"Confirmado",paid:"Pagado",cancelled:"Anulado",accepted:"Aceptado",default:"Por tratar"}},
  hi: {client_dashboard:{my_files:"मेरे केस",loading:"लोड हो रहा है...",retry:"फिर कोशिश करें",load_error:"आपका ग्राहक डेटा लोड नहीं हो सका।",no_file:"कोई केस नहीं",no_file_description:"अभी तक आपके खाते में कोई केस दर्ज नहीं है।",first_file:"अपना पहला केस बनाएं",details:"विवरण देखें",my_orders:"मेरे ऑर्डर",no_order:"कोई पुष्ट बुकिंग नहीं।",passenger:"यात्री",ticket:"टिकट देखें",cancel:"रद्द करें",appointments:"मेरे अपॉइंटमेंट",no_appointment:"कोई अपॉइंटमेंट निर्धारित नहीं।",make_appointment:"अपॉइंटमेंट लें",notifications:"मेरी सूचनाएं देखें",quick_access:"त्वरित पहुंच",services_catalogue:"सेवा कैटलॉग",book_ticket:"टिकट बुक करें",profile_hint:"आपकी प्रोफ़ाइल लॉगिन के समय उपयोग किए गए ईमेल पते से जुड़ी है।"},service_detail:{eyebrow:"सेवा",delay:"अवधि",documents:"आवश्यक दस्तावेज़",open_file:"केस खोलें",loading:"सेवा लोड हो रही है...",unavailable:"सेवा अनुपलब्ध",unavailable_description:"यह सेवा मौजूद नहीं है या अब उपलब्ध नहीं है।",back:"कैटलॉग पर वापस",load_error:"यह सेवा लोड नहीं हो सकी।"},notifications:{eyebrow:"ट्रैकिंग",title:"सूचनाएं",empty:"अभी कोई सूचना नहीं।"},footer:{tagline:"गतिशीलता और सरल प्रक्रियाएं",copyright:"सर्वाधिकार सुरक्षित।",services:"सेवाएं",journeys:"यात्राएं"},status:{pending:"लंबित",en_cours:"प्रगति पर",en_validation:"जांच में",documents_requis:"दस्तावेज़ आवश्यक",confirmed:"पुष्ट",paid:"भुगतान किया",cancelled:"रद्द",accepted:"स्वीकृत",default:"प्रक्रिया में"}},
  zh: {client_dashboard:{my_files:"我的档案",loading:"加载中...",retry:"重试",load_error:"无法加载您的客户数据。",no_file:"暂无档案",no_file_description:"您的账户还没有档案。",first_file:"创建我的第一个档案",details:"查看详情",my_orders:"我的订单",no_order:"暂无已确认的预订。",passenger:"乘客",ticket:"查看车票",cancel:"取消",appointments:"我的预约",no_appointment:"暂无预约。",make_appointment:"预约",notifications:"查看我的通知",quick_access:"快速入口",services_catalogue:"服务目录",book_ticket:"预订车票",profile_hint:"您的个人资料与登录时使用的电子邮箱关联。"},service_detail:{eyebrow:"服务",delay:"办理时限",documents:"所需文件",open_file:"创建档案",loading:"正在加载服务...",unavailable:"服务不可用",unavailable_description:"该服务不存在或已下架。",back:"返回目录",load_error:"无法加载该服务。"},notifications:{eyebrow:"跟踪",title:"通知",empty:"暂无通知。"},footer:{tagline:"出行与简化手续",copyright:"版权所有。",services:"服务",journeys:"行程"},status:{pending:"待处理",en_cours:"处理中",en_validation:"审核中",documents_requis:"缺少文件",confirmed:"已确认",paid:"已支付",cancelled:"已取消",accepted:"已受理",default:"待处理"}},
}

const feedbackTranslations = {
  fr: { logging_in: 'Connexion en cours...', admin_success: 'Connexion administrateur réussie. Redirection vers le back-office...', advisor_success: 'Connexion conseiller réussie. Redirection vers votre espace...', client_success: 'Connexion réussie. Redirection vers votre espace...', login_error: 'La connexion a échoué. Vérifiez vos identifiants.' },
  en: { logging_in: 'Signing in...', admin_success: 'Administrator sign-in successful. Redirecting to the back office...', advisor_success: 'Advisor sign-in successful. Redirecting to your area...', client_success: 'Sign-in successful. Redirecting to your area...', login_error: 'Sign-in failed. Check your credentials.' },
  ru: { logging_in: 'Выполняется вход...', admin_success: 'Вход администратора выполнен. Перенаправление в панель управления...', advisor_success: 'Вход консультанта выполнен. Перенаправление в ваш кабинет...', client_success: 'Вход выполнен. Перенаправление в ваш кабинет...', login_error: 'Не удалось войти. Проверьте ваши данные.' },
}

const fallbackAdditions = {
  fr: {
    common: { error: 'Une erreur est survenue.', load_error: 'Impossible de charger les données.', select: 'Sélectionner', no_services: 'Aucune prestation disponible pour le moment.', view_details: 'Voir les détails', load_services_error: 'Impossible de charger les prestations.', load_catalogue_error: 'Impossible de charger le catalogue.' },
    catalogue: { title: 'Catalogue', lead: 'Parcourez les prestations et ouvrez un dossier.' },
    booking: { slot: 'Créneau' },
  },
  en: {
    common: { error: 'Something went wrong.', load_error: 'Unable to load the data.', select: 'Select', no_services: 'No services are available at the moment.', view_details: 'View details', load_services_error: 'Unable to load services.', load_catalogue_error: 'Unable to load the catalogue.' },
    catalogue: { title: 'Catalogue', lead: 'Browse the services and open a file.' },
    booking: { slot: 'Time slot' },
  },
  ru: {
    common: { error: 'Произошла ошибка.', load_error: 'Не удалось загрузить данные.', select: 'Выбрать', no_services: 'Сейчас нет доступных услуг.', view_details: 'Подробнее', load_services_error: 'Не удалось загрузить услуги.', load_catalogue_error: 'Не удалось загрузить каталог.' },
    catalogue: { title: 'Каталог', lead: 'Просмотрите услуги и откройте дело.' },
    booking: { slot: 'Время' },
  },
  es: {
    common: { error: 'Se ha producido un error.', load_error: 'No se pudieron cargar los datos.', select: 'Seleccionar', no_services: 'No hay servicios disponibles por el momento.', view_details: 'Ver detalles', load_services_error: 'No se pudieron cargar los servicios.', load_catalogue_error: 'No se pudo cargar el catálogo.' },
    catalogue: { title: 'Catálogo', lead: 'Explora los servicios y abre un expediente.' },
    booking: { slot: 'Horario' },
  },
  hi: {
    common: { error: 'कोई त्रुटि हुई।', load_error: 'डेटा लोड नहीं हो सका।', select: 'चुनें', no_services: 'फिलहाल कोई सेवा उपलब्ध नहीं है।', view_details: 'विवरण देखें', load_services_error: 'सेवाएं लोड नहीं हो सकीं।', load_catalogue_error: 'कैटलॉग लोड नहीं हो सका।' },
    catalogue: { title: 'कैटलॉग', lead: 'सेवाएं देखें और केस खोलें।' },
    booking: { slot: 'समय' },
  },
  zh: {
    common: { error: '发生错误。', load_error: '无法加载数据。', select: '选择', no_services: '目前没有可用服务。', view_details: '查看详情', load_services_error: '无法加载服务。', load_catalogue_error: '无法加载目录。' },
    catalogue: { title: '目录', lead: '浏览服务并创建档案。' },
    booking: { slot: '时间段' },
  },
}

function mergeDeep(target, source) {
  const output = { ...(target || {}) }
  for (const [key, value] of Object.entries(source || {})) {
    if (value && typeof value === 'object' && !Array.isArray(value)) {
      output[key] = mergeDeep(output[key], value)
    } else {
      output[key] = value
    }
  }
  return output
}

i18n.use(LanguageDetector).use(initReactI18next).init({
  resources: {
    fr: { translation: mergeDeep({ ...fr, ui: uiTranslations.fr, dossier: dossierTranslations.fr, ...interfaceTranslations.fr, feedback: feedbackTranslations.fr }, fallbackAdditions.fr), legacy: translations.fr },
    en: { translation: mergeDeep({ ...en, ui: uiTranslations.en, dossier: dossierTranslations.en, ...interfaceTranslations.en, feedback: feedbackTranslations.en }, fallbackAdditions.en), legacy: translations.en },
    ru: { translation: mergeDeep({ ...ru, ui: uiTranslations.ru, dossier: dossierTranslations.ru, ...interfaceTranslations.ru, feedback: feedbackTranslations.ru }, fallbackAdditions.ru), legacy: translations.ru },
    es: { translation: mergeDeep({ ...es, ui: uiTranslations.es, dossier: dossierTranslations.es, ...interfaceTranslations.es, feedback: feedbackTranslations.es }, fallbackAdditions.es), legacy: translations.es },
    hi: { translation: mergeDeep({ ...hi, ui: uiTranslations.hi, dossier: dossierTranslations.hi, ...interfaceTranslations.hi, feedback: feedbackTranslations.hi }, fallbackAdditions.hi), legacy: translations.hi },
    zh: { translation: mergeDeep({ ...zh, ui: uiTranslations.zh, dossier: dossierTranslations.zh, ...interfaceTranslations.zh, feedback: feedbackTranslations.zh }, fallbackAdditions.zh), legacy: translations.zh },
  },
  fallbackLng: 'fr',
  supportedLngs: ['fr', 'en', 'ru', 'es', 'hi', 'zh'],
  interpolation: { escapeValue: false },
  detection: { order: ['localStorage', 'navigator'], lookupLocalStorage: 'i18nextLng', caches: ['localStorage'] },
})

export default i18n
