import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'
import fr from './locales/fr.json'
import en from './locales/en.json'
import ru from './locales/ru.json'
import { translations } from './data/translations'

const dossierTranslations = {
  fr: { eyebrow: 'Nouvelle demande', title: 'Ouvrir un dossier', service: 'Prestation', service_placeholder: 'Sélectionner une prestation', nationality: 'Nationalité', nationality_placeholder: 'Ex : Camerounaise', destination: 'Destination', destination_placeholder: 'Ex : France', motif: 'Motif de la demande', motif_placeholder: 'Décrivez le motif de votre demande...', document: 'Pièce justificative', file_hint: 'Formats acceptés : PDF, JPG, PNG · Max 5 Mo', submit: 'Soumettre le dossier', submitting: 'Envoi en cours...', success_title: 'Dossier soumis avec succès !', success_desc: 'Votre dossier a été créé. Un conseiller vous contactera sous 24h.', redirecting: 'Redirection vers votre espace client...', err_service: 'Veuillez choisir une prestation', err_nationality: 'La nationalité est requise', err_motif: 'Le motif est requis', err_document: 'Au moins un document est requis' },
  en: { eyebrow: 'New request', title: 'Open a file', service: 'Service', service_placeholder: 'Select a service', nationality: 'Nationality', nationality_placeholder: 'e.g. Cameroonian', destination: 'Destination', destination_placeholder: 'e.g. France', motif: 'Reason for request', motif_placeholder: 'Describe the reason for your request...', document: 'Supporting document', file_hint: 'Accepted formats: PDF, JPG, PNG · Max 5 MB', submit: 'Submit file', submitting: 'Submitting...', success_title: 'File submitted successfully!', success_desc: 'Your file has been created. An advisor will contact you within 24h.', redirecting: 'Redirecting to your client area...', err_service: 'Please choose a service', err_nationality: 'Nationality is required', err_motif: 'Reason is required', err_document: 'At least one document is required' },
  ru: { eyebrow: 'Новый запрос', title: 'Открыть дело', service: 'Услуга', service_placeholder: 'Выберите услугу', nationality: 'Гражданство', nationality_placeholder: 'Например: Камерун', destination: 'Направление', destination_placeholder: 'Например: Франция', motif: 'Причина запроса', motif_placeholder: 'Опишите причину вашего запроса...', document: 'Подтверждающий документ', file_hint: 'Допустимые форматы: PDF, JPG, PNG · Макс. 5 МБ', submit: 'Отправить дело', submitting: 'Отправка...', success_title: 'Дело успешно отправлено!', success_desc: 'Ваше дело создано. Консультант свяжется с вами в течение 24 часов.', redirecting: 'Перенаправление в личный кабинет...', err_service: 'Выберите услугу', err_nationality: 'Требуется гражданство', err_motif: 'Требуется причина', err_document: 'Необходим хотя бы один документ' },
}

const interfaceTranslations = {
  fr: { client_dashboard: { my_files: 'Mes dossiers', loading: 'Chargement...', retry: 'Réessayer', load_error: 'Impossible de charger vos données client.', no_file: 'Aucun dossier', no_file_description: "Aucun dossier n'est encore enregistré pour votre compte.", first_file: 'Créer mon premier dossier', details: 'Voir le détail', my_orders: 'Mes commandes', no_order: 'Aucune réservation confirmée.', passenger: 'passager', ticket: 'Voir le billet', cancel: 'Annuler', appointments: 'Mes rendez-vous', no_appointment: 'Aucun rendez-vous planifié.', make_appointment: 'Prendre rendez-vous', notifications: 'Voir mes notifications', quick_access: 'Accès rapide', services_catalogue: 'Catalogue des prestations', book_ticket: 'Réserver un billet', profile_hint: 'Votre profil est associé à l’adresse saisie lors de la connexion.' }, notifications: { eyebrow: 'Suivi', title: 'Notifications', empty: 'Aucune notification pour le moment.' }, footer: { tagline: 'Mobilité et démarches simplifiées', copyright: 'Tous droits réservés.', services: 'Prestations', journeys: 'Trajets' }, status: { pending: 'En attente', en_cours: 'En cours', en_validation: 'En validation', documents_requis: 'Pièces manquantes', confirmed: 'Confirmé', paid: 'Payé', cancelled: 'Annulé', accepted: 'Accepté', default: 'À traiter' } },
  en: { client_dashboard: { my_files: 'My files', loading: 'Loading...', retry: 'Retry', load_error: 'Unable to load your client data.', no_file: 'No files', no_file_description: 'No file has been registered for your account yet.', first_file: 'Create my first file', details: 'View details', my_orders: 'My orders', no_order: 'No confirmed booking.', passenger: 'passenger', ticket: 'View ticket', cancel: 'Cancel', appointments: 'My appointments', no_appointment: 'No appointment scheduled.', make_appointment: 'Make an appointment', notifications: 'View my notifications', quick_access: 'Quick access', services_catalogue: 'Services catalogue', book_ticket: 'Book a ticket', profile_hint: 'Your profile is linked to the email address used when signing in.' }, notifications: { eyebrow: 'Tracking', title: 'Notifications', empty: 'No notifications at the moment.' }, footer: { tagline: 'Mobility and simplified procedures', copyright: 'All rights reserved.', services: 'Services', journeys: 'Journeys' }, status: { pending: 'Pending', en_cours: 'In progress', en_validation: 'In validation', documents_requis: 'Missing documents', confirmed: 'Confirmed', paid: 'Paid', cancelled: 'Cancelled', accepted: 'Accepted', default: 'To process' } },
  ru: { client_dashboard: { my_files: 'Мои дела', loading: 'Загрузка...', retry: 'Повторить', load_error: 'Не удалось загрузить данные клиента.', no_file: 'Нет дел', no_file_description: 'Для вашей учётной записи пока нет дел.', first_file: 'Создать первое дело', details: 'Подробнее', my_orders: 'Мои заказы', no_order: 'Нет подтверждённых бронирований.', passenger: 'пассажир', ticket: 'Посмотреть билет', cancel: 'Отменить', appointments: 'Мои встречи', no_appointment: 'Нет запланированных встреч.', make_appointment: 'Записаться на встречу', notifications: 'Посмотреть уведомления', quick_access: 'Быстрый доступ', services_catalogue: 'Каталог услуг', book_ticket: 'Забронировать билет', profile_hint: 'Ваш профиль связан с адресом электронной почты, указанным при входе.' }, notifications: { eyebrow: 'Отслеживание', title: 'Уведомления', empty: 'Сейчас уведомлений нет.' }, footer: { tagline: 'Мобильность и упрощённые процедуры', copyright: 'Все права защищены.', services: 'Услуги', journeys: 'Маршруты' }, status: { pending: 'Ожидание', en_cours: 'В работе', en_validation: 'На проверке', documents_requis: 'Необходимы документы', confirmed: 'Подтверждено', paid: 'Оплачено', cancelled: 'Отменено', accepted: 'Принято', default: 'В обработку' } },
}

const feedbackTranslations = {
  fr: { logging_in: 'Connexion en cours...', admin_success: 'Connexion administrateur réussie. Redirection vers le back-office...', advisor_success: 'Connexion conseiller réussie. Redirection vers votre espace...', client_success: 'Connexion réussie. Redirection vers votre espace...', login_error: 'La connexion a échoué. Vérifiez vos identifiants.' },
  en: { logging_in: 'Signing in...', admin_success: 'Administrator sign-in successful. Redirecting to the back office...', advisor_success: 'Advisor sign-in successful. Redirecting to your area...', client_success: 'Sign-in successful. Redirecting to your area...', login_error: 'Sign-in failed. Check your credentials.' },
  ru: { logging_in: 'Выполняется вход...', admin_success: 'Вход администратора выполнен. Перенаправление в панель управления...', advisor_success: 'Вход консультанта выполнен. Перенаправление в ваш кабинет...', client_success: 'Вход выполнен. Перенаправление в ваш кабинет...', login_error: 'Не удалось войти. Проверьте ваши данные.' },
}

i18n.use(LanguageDetector).use(initReactI18next).init({
  resources: {
    fr: { translation: { ...fr, dossier: dossierTranslations.fr, ...interfaceTranslations.fr, feedback: feedbackTranslations.fr }, legacy: translations.fr },
    en: { translation: { ...en, dossier: dossierTranslations.en, ...interfaceTranslations.en, feedback: feedbackTranslations.en }, legacy: translations.en },
    ru: { translation: { ...ru, dossier: dossierTranslations.ru, ...interfaceTranslations.ru, feedback: feedbackTranslations.ru }, legacy: translations.ru },
  },
  fallbackLng: 'fr',
  supportedLngs: ['fr', 'en', 'ru'],
  interpolation: { escapeValue: false },
  detection: { order: ['localStorage', 'navigator'], lookupLocalStorage: 'i18nextLng', caches: ['localStorage'] },
})

export default i18n
